### ISSUE TITLE
nice page!

### ISSUE THREAD

**Issue by S-PScripts** [wea-f/ByePassHub#1]
since you don't have discussions i'll have to make it an issue...

anyways, here's another ai link: https://talkai.info/chat

also, the buypass links you have do not work due to a bug from bypassi's original. use one of these ones:
https://playful-meringue-fb58bc.netlify.app/
https://kf8pr9d.micasuki.com/ 
https://sort.darkshade.design/ 

i also recommend checking hop links often. they do get taken down quick (as with all the interstellars. also don't add too many interstellars as grobby did as the discord admins including bubbo were really fricking mad at him)

**Comment by wea-f** [comment]
ty for the new links and advice, what specific discord server is this happening in cause I'm not in it.

**Comment by S-PScripts** [comment]
> ty for the new links and advice, what specific discord server is this happening in cause I'm not in it.

deblok server. the owner put him on the board of retards saying how grobby removed the interstellars and debloks then readded them.
