### ISSUE TITLE
unsafe bookmarklet

### ISSUE THREAD

**Issue by Babydino2-2-3** [wea-f/ByePassHub#11]
the fortnite unblocked bookmarklet literally just tries to send your epic account info to someone LOL
this is just basic javascript reading im not sure how this got through minus being actively malicious or a severe lack of attention, both of which on a repo of this size is HEAVILY concerning

**Comment by wea-f** [comment]
Oh SHOOT I didn't realize that, after looking through it, its so obv omg. I found the bookmarklet from a Google doc proxy collection (I think it was Worldly Networks), I don't remember what was going through my head, but I clearly didn't read what the code was doing. Anyways I removed it, thank you so much for noticing this.
