### ISSUE TITLE
Links I made for a custom proxy

### ISSUE THREAD

**Issue by WatchGamingVideos** [wea-f/ByePassHub#14]
nvd123s tools LINKS (may go down but add them)

https://nvd123s-utilities.vercel.app
https://apple-trees-apple-trees-85b6bf01.koyeb.app/

I'll post more soon

**Comment by WatchGamingVideos** [comment]
Also https://ronaldo-farm.vercel.app

**Comment by wea-f** [comment]
Cool links! Unfortunately I do not add vercel.app or koyeb.app links to my list because it's blocked for me and other people

**Comment by WatchGamingVideos** [comment]
yea and all the Roblox links and literally almost every one of ur links is blocked for me lol.

Can u at least get new Roblox ones or tell us how to make them?

Or just add these links?

Whatever happens, thank you.

> Cool links! Unfortunately I do not add vercel.app or koyeb.app links to my list because it's blocked for me and other people

**Comment by WatchGamingVideos** [comment]
Also how could I make a non vercel or something link for free

is there a way like to get free .org domains or something

**Comment by wea-f** [comment]
I haven't found any new Roblox links, but you can check out other proxy/link lists here: https://github.com/wea-f/ByePassHub/blob/main/mainUnblockers.md#other-lists-like-this-one--games-proxies-movies-and-even-more-links--links-may-or-may-not-work

To make a non-vercel link for free, follow the freedns tutorial in the MakeYourOwnLink file: https://github.com/wea-f/ByePassHub/blob/main/MakeYourOwnLink.md#making-links-via-freedns

**Comment by WatchGamingVideos** [comment]
Oh freeDNS I gotta try that at home 

> I haven't found any new Roblox links, but you can check out other proxy/link lists here: https://github.com/wea-f/ByePassHub/blob/main/mainUnblockers.md#other-lists-like-this-one--games-proxies-movies-and-even-more-links--links-may-or-may-not-work
> 
> To make a non-vercel link for free, follow the freedns tutorial in the MakeYourOwnLink file: https://github.com/wea-f/ByePassHub/blob/main/MakeYourOwnLink.md#making-links-via-freedns
