### ISSUE TITLE
I need rammerhead browser/proxy links

### ISSUE THREAD

**Issue by Brickboxing** [wea-f/ByePassHub#17]
I need links, i cant use discord so please someone send the links here, and please have them last long 3 weeks+ or more

**Comment by wea-f** [comment]
Hi @Brickboxing, there are 65+ Rammerhead links [here](https://github.com/wea-f/ByePassHub/blob/main/mainUnblockers.md#rammerhead--web-browser), in the mainUnblockders.md file. And all of them should be working and should be up for more than 3 weeks.

**Comment by Brickboxing** [comment]
I have lightspeed filter so a majority of them might be blocked under security.domain-sharing, but ill try nonetheless. thank you.

**Comment by Brickboxing** [comment]
yep i tried none of them work for me, got any me more? or any other proxies like emerald? or doge?

**Comment by Brickboxing** [comment]
hey, is its possible you could make a rammerhead proxy for me and send the link in private

**Comment by wea-f** [comment]
Alright I found  some more rammerhead links: If all of these links don't work, I'll send other proxies and maybe try to make one.
 https://cancoke.404.mn/ 
[ https://payday3.echa.xyz/](https://payday3.echa.xyz/) 
[ https://edgesucks.uk.to/](https://edgesucks.uk.to/) 
[ https://roguepoke.soon.it.soon.it/](https://roguepoke.soon.it.soon.it/) 
[ https://port0of.norushcharge.com/](https://port0of.norushcharge.com/) 
[ https://hrju65.46-whitwell.co.uk/](https://hrju65.46-whitwell.co.uk/) 
[ https://jtyru54.cmiranda.ar/](https://jtyru54.cmiranda.ar/) 
https://kujtk67.fromsoelberg.dk/ 
https://rancid.vslui.net/ 
[ https://seigetime.ix.tc/](https://seigetime.ix.tc/) 
[ https://tridecagram.ix.tc/](https://tridecagram.ix.tc/) 
[ https://shellington.jumpingcrab.com/](https://shellington.jumpingcrab.com/) 
[ https://i.love.the.us.to/](https://i.love.the.us.to/) 
https://jyp.bomboclat.shop/
[ https://curlworldhunger.prayerforworldpeace.com/](https://curlworldhunger.prayerforworldpeace.com/) 
[ https://imsogoopy.69.mu/](https://imsogoopy.69.mu/) 
[ https://skibidliedrizzlered-ciscoumbre11a-c0ntrol1ed.fredvanryck.be/](https://skibidliedrizzlered-ciscoumbre11a-c0ntrol1ed.fredvanryck.be/)
 [ https://10101111000101010110110100010101001.codeforce.ru/](https://10101111000101010110110100010101001.codeforce.ru/) 
 [ https://moms.mine.bz/](https://moms.mine.bz/) 
[ https://englishhomework.unworthycause.com/](https://englishhomework.unworthycause.com/) 
[ https://hairumscarum.adonis.pt/](https://hairumscarum.adonis.pt/) 
[ https://weiener.org.jumpingcrab.com/](https://weiener.org.jumpingcrab.com/) 
[ https://rammer.duckdns.org/](https://rammer.duckdns.org/) 
[ https://putmyheartandsoulontheglock.oborenstein.com/](https://putmyheartandsoulontheglock.oborenstein.com/) 
[ https://garchomp.l5.ca/](https://garchomp.l5.ca/) 
[ https://theydontfwrhett.uhane.mx/](https://theydontfwrhett.uhane.mx/) 
[ https://ramified.hs.vc/](https://ramified.hs.vc/)
https://ejmsunblockedisgoatedshoutoutoemberandrez2am.bogpet.ro/
https://ejmsunblockedisigmadontbeplayingandleaking.bogpet.ro/
https://emberisgoatedawesomeelijahisgrimaceskibidiohio.bogpet.ro/

**Comment by Brickboxing** [comment]
AYE! it worked was able to find one! thanks bro.

**Comment by wea-f** [comment]
No problem
