### ISSUE TITLE
JUST A QUESTION

### ISSUE THREAD

**Issue by DogeClan** [wea-f/ByePassHub#19]
wea-f by chance do you have a form of preferred contact such as an email or web-based chat platform?

**Comment by wea-f** [comment]
Yes, why do you ask?

**Comment by DogeClan** [comment]
If you are interested: I can give you more details, but I would rather provide you with the info via your preferred email/chat platform.

**Comment by DogeClan** [comment]
Sorry for the late response

**Comment by DogeClan** [comment]
Okay, thanks
