### ISSUE TITLE
Like none of the links work

### ISSUE THREAD

**Issue by Perplexed2** [wea-f/ByePassHub#25]
ive tried like 200 of them and for me in seattle they dont work the doge ones have worked in the past can you try and email me a direct .txt file of all of the ones you have that would be great

**Comment by DogeClan** [comment]
To find Doge Unblocker v4 links: check out the links section at the Doge Unblocker discord page.

**Comment by wea-f** [comment]
> ive tried like 200 of them and for me in seattle they dont work the doge ones have worked in the past can you try and email me a direct .txt file of all of the ones you have that would be great

Thanks for letting me know, those links were working for me a few days ago but I guess they got shut down. I just updated the file with functional links.
