### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by johnegbertgaming** [wea-f/ByePassHub#28]
can yall rename the unblockedsearchengines thing my school has some keywords in there blocked and i cant access it

**Comment by wea-f** [comment]
Do you know what specific keyword? Is it “unblocked?”

**Comment by johnegbertgaming** [comment]
yeah its unblocked

**Comment by wea-f** [comment]
Can you first try to use an unblocker to unblock that page? 

It would be really annoying to change the file name because I would have to change the file path across every other page.

**Comment by johnegbertgaming** [comment]
i didnt think of that mb lol
yeah i could do that sorry for bothering you

**Comment by wea-f** [comment]
Nah you're good 👍
