### ISSUE TITLE
Take down all Interstellar links.

### ISSUE THREAD

**Issue by MadjikDotPng** [wea-f/ByePassHub#5]
This is a request for you to take down all of the Interstellar links. There's no way we can force you but we would be grateful if you did so. If you want to include some kind of Interstellar link, include one for gointerstellar.app and our discord. Thanks!

**Comment by wea-f** [comment]
No problem, I removed all links except for gointerstellar.app and your discord. 
I got basically all of them from that Proxies 100+ doc if you aren't aware of it's existence

**Comment by MadjikDotPng** [comment]
Oh thanks! That doc was cause for quite a lot of trouble for a while, thanks for your cooperation!
