### ISSUE TITLE
Remove Night

### ISSUE THREAD

**Issue by not-amplify** [wea-f/ByePassHub#9]
Hi, Im Amplify, Co-owner of Night. Im just finna say this straight. if you dont remove Night from your leaks i will A: ban you B: you will get DMCA'ed.

**Comment by wea-f** [comment]
sorry for having leaked Night links, I didn't leak I found them from that [proxies 100+](https://docs.google.com/document/d/1nK6tJb-sxfrrQJM9bSWcAV-Fo7jHasd_dWpj4VEVg5E/edit#bookmark=kix.qnsrc8c4high) google document, anyways I removed ALL of them. I still have your discord server linked if thats okay, and I am wondering if there is any official link of Night that I can put or no?

**Comment by not-amplify** [comment]
> sorry for having leaked Night links, I didn't leak I found them from that [proxies 100+](https://docs.google.com/document/d/1nK6tJb-sxfrrQJM9bSWcAV-Fo7jHasd_dWpj4VEVg5E/edit#bookmark=kix.qnsrc8c4high) google document, anyways I removed ALL of them. I still have your discord server linked if thats okay, and I am wondering if there is any official link of Night that I can put or no?

Our links are down due to the loads of our VPS and so none of our links currently work but we are working on acquiring new servers.
